### ISSUE TITLE
error: this old-style function definition is not preceded by a prototype

### ISSUE THREAD

**Issue by usrnamealreadytaken** [CaptainThrowback/android_kernel_asus_ZS661KS#1]
Compiling kernel natively on the device in chroot. Build fails with the following error:
`../drivers/input/touchscreen/station_goodix_gtx8/goodix_cfg_bin.c:621:15: error: this old-style function definition is not preceded by a prototype [-Werror,-Wstrict-prototypes]
void exit_init() {
              ^
1 error generated.`
The issue is, there is no such function in either the file, or it's header. Will adding `-Wno-strict-prototypes` in Makefile fix the issue?
My `build_kernel-ZS661KS.sh`, modified  to run natively  :
```
#!/bin/bash


echo
echo "Issue Build Commands"
echo

mkdir -p out
export ARCH=arm64
export SUBARCH=arm64

echo
echo "Set DEFCONFIG"                                                        echo
make CC=clang AR=ar NM=nm OBJCOPY=objcopy OBJDUMP=objdump STRIP=strip O=out vendor/ZS661KS_defconfig

echo
echo "Build The Good Stuff"
echo                                                                        
make CC=clang AR=ar NM=nm OBJCOPY=objcopy OBJDUMP=objdump STRIP=strip O=out -j4

echo
echo "Compile DTBs"
echo                                                                        
find out/arch/arm64/boot/dts -name '*.dtb' -exec cat {} + > out/arch/arm64/boot/dtb.img

echo
echo "Build Complete!"
echo
```

**Comment by CaptainThrowback** [comment]
I don't know anything about this. Kernel compiles fine for me in WSL and I know nothing about chroot or building it on the device. This is just the stock kernel source with very minor changes. I have no plans on fixing whatever is causing your issue, but if you do figure it out, feel free to submit a PR and I'll think about merging it.

**Comment by usrnamealreadytaken** [comment]
Could you please provide the cross-compiled toolchain you've used. I can't get it to work with my clang version

**Comment by CaptainThrowback** [comment]
`Linux version 4.19.81-perf+ (throwback@CAPTAIN-DESKTOP) (Android (6607189 based on r383902c) clang version 11.0.3 (https://android.googlesource.com/toolchain/llvm-project b397f81060ce6d701042b782172ed13bee898b79)) #4 SMP PREEMPT Sun Oct 4 17:37:03 EDT 2020`
